parameters:
  admin_prefix:     '%env(resolve:ADMIN_PREFIX)%'
  download_path:    '%kernel.project_dir%/downloads'
  videos_path:      '%download_path%/videos'
  sources_path:     '%download_path%/sources'
  image_resize_key: '%env(resolve:IMAGE_RESIZE_KEY)%'
  twitter_key:      '%env(resolve:TWITTER_KEY)%'
  twitter_secret:   '%env(resolve:TWITTER_SECRET)%'
  container.dumper.inline_factories: true
  container.dumper.inline_class_loader: true

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false
    bind:
      $videosPath: '%videos_path%'
      $projectDir: '%kernel.project_dir%'

  _instanceof:
    App\Core\Breadcrumb\BreadcrumbGeneratorInterface:
      tags: ['app.breadcrumb']

  Redis:
    class: \Predis\Client
    arguments:
      - '%env(REDIS_URL)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

  App\Http\Controller\:
    resource: '../src/Http/Controller'
    tags: ['controller.service_arguments']

  App\Http\Admin\Controller\:
    resource: '../src/Http/Admin/Controller'
    tags: ['controller.service_arguments']

  App\Http\Api\Controller\:
    resource: '../src/Http/Api/Controller'
    tags: ['controller.service_arguments']

  Everyman\Neo4j\Client:
    factory: ['App\Core\Services\Neo4jClientFactory', 'createClient']
    arguments: ['neo4j', 'neo4j', 'neo']

  App\Infrastructure\Storage\Naming\IdDirectoryNamer:
    public: true

  App\Http\Admin\Firewall\AdminRequestListener:
    arguments: ['%admin_prefix%']

  Knp\Bundle\PaginatorBundle\Helper\Processor: ~

  App\Core\Helper\Paginator\PaginatorInterface:
    class: App\Core\Helper\Paginator\KnpPaginator

  App\Core\Twig\TwigBreadcrumbExtension:
    arguments: [!tagged_iterator app.breadcrumb]

  App\Core\UploaderBundle\PropertyGroupedDirectoryNamer:
    public: true

  App\Infrastructure\Mercure\Service\CookieGenerator:
    arguments:
      $secret: '%env(resolve:MERCURE_SUBSCRIBER_KEY)%'

  App\Core\Twig\TwigAssetExtension:
    arguments:
      $assetPath: '%kernel.project_dir%/public/assets'
      $env: '%kernel.environment%'

  App\Infrastructure\Image\ImageResizer:
    arguments: ['%image_resize_key%']

  App\Core\Orm\DoctrineSchemaListener:
    tags: ['doctrine.event_subscriber']

  App\Core\Services\TwitterService:
    arguments: ['%twitter_key%', '%twitter_secret%']

  App\Infrastructure\Queue\FailedJobsService:
    arguments: ['@messenger.transport.failed']

  App\Infrastructure\Queue\ScheduledJobsService:
    arguments:
      $dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

  App\Infrastructure\Spam\SpamService:
    arguments: [['App\Domain\Forum\Entity\Topic', 'App\Domain\Forum\Entity\Message']]

  App\Command\DumpCommand:
    arguments:
      $projectPath: '%kernel.project_dir%/var'
      $filesystem: '@dropbox_filesystem'

  App\Infrastructure\Storage\DropboxFilesystemFactory:
    arguments:
      - '%env(DROPBOX_TOKEN)%'

  dropbox_filesystem:
    class: League\Flysystem\Filesystem
    factory: ['@App\Infrastructure\Storage\DropboxFilesystemFactory', 'createFilesystem']
